import { useEffect, useState } from 'react';
import { api, type Question } from '../api';
import { QuestionCard } from '../components/QuestionCard';

export function BankPage() {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [exporting, setExporting] = useState(false);

  async function load(): Promise<void> {
    const page = await api.listQuestions({ status: 'approved', pageSize: 100 });
    setQuestions(page.items);
  }

  useEffect(() => {
    void load().catch((caught: unknown) => {
      setError(caught instanceof Error ? caught.message : 'Could not load the bank.');
    });
  }, []);

  async function onExport(): Promise<void> {
    setExporting(true);
    try {
      const gift = await api.exportGift();
      const blob = new Blob([gift], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = 'itemforge-bank.gift';
      anchor.click();
      URL.revokeObjectURL(url);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'Export failed.');
    } finally {
      setExporting(false);
    }
  }

  return (
    <section>
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold">Question bank</h1>
          <p className="mt-2 max-w-2xl text-ink-600">
            Items an educator has accepted. Nothing generated by the model reaches this list on its
            own.
          </p>
        </div>
        <button type="button" className="btn-secondary" disabled={exporting || questions.length === 0} onClick={() => void onExport()}>
          {exporting ? 'Exporting…' : 'Export Moodle GIFT'}
        </button>
      </div>
      {error ? (
        <p className="mt-4 text-sm text-red-800" role="alert">
          {error}
        </p>
      ) : null}
      {questions.length === 0 ? (
        <p className="mt-8 text-ink-600">The bank is empty.</p>
      ) : (
        <div className="mt-6 space-y-4">
          {questions.map((question) => (
            <QuestionCard
              key={question.id}
              question={question}
              mode="bank"
              onChanged={(updated) =>
                setQuestions((current) => current.filter((item) => item.id !== updated.id))
              }
            />
          ))}
        </div>
      )}
    </section>
  );
}
